### ISSUE TITLE
yq: error: argument files: can't open 'notebooks'

### ISSUE THREAD

**Issue by muralikodali** [alichtman/fzf-notes#5]
fzf-notes giving following error : 

```
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'notebooks': [Errno 2] No such file or directory: 'notebooks'
ERROR: Invalid notebook name: .
```

yq version is :  2.10.1

**Comment by alichtman** [comment]
Can you post your config file?

**Comment by muralikodali** [comment]
configuration file : 

```
notebooks:
  default: /home/xxxx/NotesAll/viki
  cheat: /home/xxxx/.cheat
  cheats: /home/xxxx/.navi/cheats
  shells: /home/xxxx/shells
```

**Comment by alichtman** [comment]
Where does this file live? It looks ok to me, so ~my guess is that the config file isn't being found. Your XDG settings might not be properly set. Can you share those?~

**Comment by muralikodali** [comment]
configuration file is located at ~/.config/fzf-notes.

fzf-notes -C opening configuration file without any error.

My OS is Arch Linux and yq version is 2.10.1

**Comment by alichtman** [comment]
Here's what mine looks like:

```yaml
notebooks:
  default: ~/Desktop/Development/notes
  scratchpad: ~/scratchpad
```

```bash
$ yq --version 
yq version 3.3.0
```

Try updating `yq`.
